# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
    - build
    - test

before_script:
  - echo $pwd # debug
  - set GRADLE_USER_HOME=$pwd\.gradle
  - dir

build:
  stage: build
  script: 
    - gradlew assemble
  artifacts:
    paths:
        - .\libs\*.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .\build
      - .\.gradle
  only:
    - master



test:
  stage: test
  script: 
    - gradlew check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - .\build
      - .\.gradle


after_script:
  - echo "End CI"