image: java:13-jdk

stages:
  - build
  - test
  - deploy

before_script:
  - echo $PWD # debug
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - set GRADLE_USER_HOME=$PWD/MacySprings/.gradle
  - set JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/bin/"
  - chmod +x ./MacySprings/gradlew
  - sed 's/${MYSQL_HOST:localhost}/seproject-aws.cdptc7ikhvme.us-east-2.rds.amazonaws.com/g' ./MacySprings/src/main/resources/application.properties > temp.properties
  - mv temp.properties ./MacySprings/src/main/resources/application.properties
  - sed 's/S0m3!p@ssw0rd/eJTSU3cB99c24gVd/g' ./MacySprings/src/main/resources/application.properties > temp.properties
  - mv temp.properties ./MacySprings/src/main/resources/application.properties
  - cat ./MacySprings/src/main/resources/application.properties
  
cache:
  paths:
    - MacySprings/.gradle/wrapper
    - MacySprings/.gradle/caches

build:
  stage: build
  script:
    - ./MacySprings/gradlew --project-dir MacySprings assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./MacySprings/gradlew --project-dir MacySprings check
    - ./MacySprings/gradlew --project-dir MacySprings test


after_script:
  - echo "End CI"